CREATE TABLE IF NOT EXISTS DATA_EXPORT_PARAMETER_MAPPING
(
  DATA_EXPORT varchar(256),
  PARAMETER varchar(256),
  PARAMETER_LABEL varchar(256),
  TRANSFORMATION varchar(256),
  DEFAULT_VALUE varchar(256)
);
